# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threshold_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 50, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit_x = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_x.setGeometry(QtCore.QRect(140, 50, 113, 20))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.checkBox_x = QtWidgets.QCheckBox(Dialog)
        self.checkBox_x.setGeometry(QtCore.QRect(280, 50, 71, 16))
        self.checkBox_x.setObjectName("checkBox_x")
        self.lineEdit_y = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_y.setGeometry(QtCore.QRect(140, 90, 113, 20))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 54, 12))
        self.label_2.setObjectName("label_2")
        self.checkBox_y = QtWidgets.QCheckBox(Dialog)
        self.checkBox_y.setGeometry(QtCore.QRect(280, 90, 71, 16))
        self.checkBox_y.setObjectName("checkBox_y")
        self.lineEdit_z = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_z.setGeometry(QtCore.QRect(140, 130, 113, 20))
        self.lineEdit_z.setObjectName("lineEdit_z")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 54, 12))
        self.label_3.setObjectName("label_3")
        self.checkBox_z = QtWidgets.QCheckBox(Dialog)
        self.checkBox_z.setGeometry(QtCore.QRect(280, 130, 71, 16))
        self.checkBox_z.setObjectName("checkBox_z")
        self.lineEdit_r = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_r.setGeometry(QtCore.QRect(140, 170, 113, 20))
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 170, 54, 12))
        self.label_4.setObjectName("label_4")
        self.checkBox_r = QtWidgets.QCheckBox(Dialog)
        self.checkBox_r.setGeometry(QtCore.QRect(280, 170, 71, 16))
        self.checkBox_r.setObjectName("checkBox_r")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)      # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)      # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置阈值-标准模式"))
        self.label.setText(_translate("Dialog", "X方向阈值"))
        self.checkBox_x.setText(_translate("Dialog", "是否监控"))
        self.label_2.setText(_translate("Dialog", "Y方向阈值"))
        self.checkBox_y.setText(_translate("Dialog", "是否监控"))
        self.label_3.setText(_translate("Dialog", "Z方向阈值"))
        self.checkBox_z.setText(_translate("Dialog", "是否监控"))
        self.label_4.setText(_translate("Dialog", "RMSE阈值"))
        self.checkBox_r.setText(_translate("Dialog", "是否监控"))
